# Generated by Django 6.0.5 on 2026-06-12 10:49

import apps.channel.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('invite_token', models.CharField(default=apps.channel.models.generate_invite_token, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='channel.channel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='channel.channel')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_members_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel__name', 'display_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBroadcastDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('provider_name', models.CharField(default='sendafrica', max_length=40)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField()),
                ('credits_used', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='channel.channelbroadcast')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_deliveries', to='channel.channelmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_credits', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(default='sendafrica', max_length=40)),
                ('sender_id', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_topup_reference', models.CharField(blank=True, default='', max_length=120)),
                ('last_topup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='channel.channel')),
            ],
            options={
                'ordering': ['channel__name'],
            },
        ),
        migrations.AddIndex(
            model_name='channelbroadcast',
            index=models.Index(fields=['channel', 'status'], name='channel_cha_channel_9c1c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelbroadcast',
            index=models.Index(fields=['channel', '-created_at'], name='channel_cha_channel_356eab_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmember',
            index=models.Index(fields=['channel', 'is_active'], name='channel_cha_channel_08f88e_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmember',
            index=models.Index(fields=['channel', 'role'], name='channel_cha_channel_1155a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelmember',
            constraint=models.UniqueConstraint(fields=('channel', 'user'), name='unique_channel_member'),
        ),
        migrations.AddIndex(
            model_name='channelbroadcastdelivery',
            index=models.Index(fields=['broadcast', 'status'], name='channel_cha_broadca_bb07a0_idx'),
        ),
        migrations.AddIndex(
            model_name='channelbroadcastdelivery',
            index=models.Index(fields=['broadcast', 'recipient_phone'], name='channel_cha_broadca_4754df_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelbroadcastdelivery',
            constraint=models.UniqueConstraint(fields=('broadcast', 'member'), name='unique_channel_broadcast_delivery_per_member'),
        ),
    ]
