# Generated by Django 6.0.5 on 2026-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelwallet',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
