# Generated by Django 6.0.5 on 2026-05-31 14:06

import apps.classcomms.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_broadcasts', to='classes.class')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_comms_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassCommsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=apps.classcomms.models.generate_public_token, max_length=255, unique=True)),
                ('public_registration_enabled', models.BooleanField(default=True)),
                ('default_sender_name', models.CharField(blank=True, default='', max_length=80)),
                ('registration_hint', models.CharField(blank=True, default='Register your name and phone number to receive class updates.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comms_profile', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_comms_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['class_obj__name'],
            },
        ),
        migrations.CreateModel(
            name='ClassCommsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_credits', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(default='africastalking', max_length=40)),
                ('sender_id', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_topup_reference', models.CharField(blank=True, default='', max_length=120)),
                ('last_topup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comms_wallet', to='classes.class')),
            ],
            options={
                'ordering': ['class_obj__name'],
            },
        ),
        migrations.CreateModel(
            name='ClassContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('consent_granted', models.BooleanField(default=True)),
                ('consent_source', models.CharField(choices=[('manual', 'Manual'), ('public', 'Public registration'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_contacts', to='classes.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_comms_created_contacts', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_comms_registered_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassBroadcastDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('provider_name', models.CharField(default='africastalking', max_length=40)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField()),
                ('credits_used', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='classcomms.classbroadcast')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_deliveries', to='classcomms.classcontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classbroadcast',
            index=models.Index(fields=['class_obj', 'status'], name='classcomms__class_o_f8c757_idx'),
        ),
        migrations.AddIndex(
            model_name='classbroadcast',
            index=models.Index(fields=['class_obj', '-created_at'], name='classcomms__class_o_ee5394_idx'),
        ),
        migrations.AddIndex(
            model_name='classcontact',
            index=models.Index(fields=['class_obj', 'is_active'], name='classcomms__class_o_da1563_idx'),
        ),
        migrations.AddIndex(
            model_name='classcontact',
            index=models.Index(fields=['class_obj', 'phone_number'], name='classcomms__class_o_ffcbeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='classcontact',
            constraint=models.UniqueConstraint(fields=('class_obj', 'phone_number'), name='unique_class_contact_phone_per_class'),
        ),
        migrations.AddIndex(
            model_name='classbroadcastdelivery',
            index=models.Index(fields=['broadcast', 'status'], name='classcomms__broadca_da38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='classbroadcastdelivery',
            index=models.Index(fields=['broadcast', 'recipient_phone'], name='classcomms__broadca_3eb4f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='classbroadcastdelivery',
            constraint=models.UniqueConstraint(fields=('broadcast', 'contact'), name='unique_broadcast_delivery_per_contact'),
        ),
    ]
