# Generated by Django 6.0.5 on 2026-06-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='search_sear_user_id_677f6a_idx',
            old_name='search_hist_user_id_idx',
        ),
    ]
