# Generated by Django 5.2.8 on 2025-11-22 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('full_path', models.TextField()),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField()),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'method'], name='core_reques_timesta_ae7bb8_idx'), models.Index(fields=['user', '-timestamp'], name='core_reques_user_id_06ebf9_idx'), models.Index(fields=['status_code', '-timestamp'], name='core_reques_status__b56483_idx')],
            },
        ),
    ]
