# Generated by Django 5.2.8 on 2025-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('code', models.CharField(max_length=32, verbose_name='otp code')),
                ('reset_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='reset token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'password reset otp',
                'verbose_name_plural': 'password reset otps',
            },
        ),
    ]
