# Generated by Django 5.2.8 on 2025-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='purpose',
            field=models.CharField(default='password_reset', max_length=32, verbose_name='purpose'),
        ),
    ]
