# Generated by Django 5.2.8 on 2025-11-27 19:34

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresetotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture. Upload an image file.', null=True, upload_to=authentication.models.profile_image_path, verbose_name='profile image'),
        ),
    ]
