# Generated by Django 5.2.8 on 2026-04-08 12:02

import apps.schedule.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name shown in the UI.', max_length=255)),
                ('calendar_type', models.CharField(choices=[('classes', 'Classes'), ('examination', 'Examination')], help_text='System calendar type. One per user for each type.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description.', null=True)),
                ('is_public_sync', models.BooleanField(default=True, help_text='Whether public token-based subscribe/download endpoints are enabled.')),
                ('share_token', models.CharField(default=apps.schedule.models.generate_share_token, help_text='Stable token used for public sync URLs.', max_length=255, unique=True)),
                ('calendar_code', models.CharField(editable=False, help_text='Short manual code used for calendar lookup.', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The Kibegi user who owns this calendar.', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['calendar_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField(help_text='When the event starts.')),
                ('end_at', models.DateTimeField(help_text='When the event ends.')),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('exam', 'Exam'), ('study', 'Study'), ('deadline', 'Deadline'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('days', models.JSONField(blank=True, help_text='List of weekdays for weekly recurrence.', null=True)),
                ('reminder_minutes', models.PositiveIntegerField(default=15)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('system', 'System')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(help_text='Calendar the event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.schedulecalendar')),
            ],
            options={
                'ordering': ['start_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSyncAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(help_text='subscribe, download, info, qr', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_access_logs', to='schedule.schedulecalendar')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='schedulecalendar',
            constraint=models.UniqueConstraint(fields=('owner', 'calendar_type'), name='unique_schedule_calendar_type_per_owner'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['calendar', 'start_at'], name='schedule_sc_calenda_6a910f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['calendar', 'event_type'], name='schedule_sc_calenda_6a0feb_idx'),
        ),
    ]
