# Generated by Django 5.2.8 on 2025-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if created by a lecturer, False for student study groups'),
        ),
    ]
