# Generated by Django 6.0.5 on 2026-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('representative', 'Representative'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
