# Generated by Django 6.0.5 on 2026-05-31 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_object_id', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('balance_credits', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(default='africastalking', max_length=40)),
                ('sender_id', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_topup_reference', models.CharField(blank=True, default='', max_length=120)),
                ('last_topup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner_content_type', 'owner_object_id')},
            },
        ),
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_object_id', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('provider_name', models.CharField(default='africastalking', max_length=40)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField()),
                ('credits_used', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_deliveries', to='contenttypes.contenttype')),
                ('sms_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sms.smsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['context_content_type', 'context_object_id'], name='sms_smsdeli_context_473c68_idx'), models.Index(fields=['sms_account', 'status'], name='sms_smsdeli_sms_acc_e5ac8d_idx')],
            },
        ),
    ]
