# Generated by Django 6.0.6 on 2026-06-15 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_document_chunk_and_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
