# Generated by Django 5.2.8 on 2025-11-23 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0004_alter_upload_class_obj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the share', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the share request', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from sharer to recipient', max_length=500)),
                ('shared_at', models.DateTimeField(auto_now_add=True, help_text='When the share request was created')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the share was accepted (null if pending/rejected)', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the share was rejected (null if pending/accepted)', null=True)),
                ('shared_by', models.ForeignKey(help_text='User who is sharing the file', on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(help_text='User receiving the file share', on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(help_text='The file being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='uploads.upload')),
            ],
            options={
                'verbose_name': 'Shared File',
                'verbose_name_plural': 'Shared Files',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['status', 'shared_at'], name='sharing_sha_status_a06145_idx'), models.Index(fields=['shared_with', 'status'], name='sharing_sha_shared__0ae47e_idx')],
                'unique_together': {('upload', 'shared_with')},
            },
        ),
    ]
