# Generated by Django 5.2.8 on 2025-11-25 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota_mb', models.DecimalField(decimal_places=2, default=50.0, help_text='Total storage quota in megabytes (default: 50MB)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('used_storage_bytes', models.BigIntegerField(default=0, help_text='Current storage used in bytes (calculated from uploaded files)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this storage record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this storage record was last updated')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='Timestamp of last storage calculation')),
                ('user', models.OneToOneField(help_text='The user this storage record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Storage',
                'verbose_name_plural': 'User Storage Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_storage_bytes', models.BigIntegerField(help_text='Storage used in bytes at this point in time', validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this storage snapshot was recorded')),
                ('user_storage', models.ForeignKey(help_text='The storage record this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='storage.userstorage')),
            ],
            options={
                'verbose_name': 'Storage Usage History',
                'verbose_name_plural': 'Storage Usage History',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user_storage', '-recorded_at'], name='storage_sto_user_st_8659e8_idx')],
            },
        ),
    ]
