# Generated by Django 5.2.8 on 2025-11-23 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='Custom nickname for the friend', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', help_text='Status of the friendship (pending or accepted)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the friend request was sent')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the friend request was accepted', null=True)),
                ('friend', models.ForeignKey(help_text='User who received the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who sent the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='friends_fri_user_id_6bc74d_idx'), models.Index(fields=['friend', 'status'], name='friends_fri_friend__ab05a6_idx')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
