"""
Django settings for kibegi_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u%i7d=u%)@k(6blq_pr^%tgo7@ktkrsh_qm%ob8w%mq-s0_=%g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['api.kibegi.com', '194.163.153.255', 'localhost', '192.168.10.144', '127.0.0.1']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'storages',

    # Local apps
    'apps.core',
    'apps.authentication',
    'apps.classes',
    'apps.uploads',
    'apps.sharing',
    'apps.friends',
    'apps.notifications',
    'apps.files',
    'apps.storage',
    'apps.schedule',
    'apps.marketplace',
    'apps.library',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'kibegi_api.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kibegi_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kibegi_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Load database configuration from environment variables
# Defaults to SQLite for development if PostgreSQL not configured
# To use PostgreSQL, set DB_ENGINE=django.db.backends.postgresql in .env
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
DB_NAME = config('DB_NAME', default='kibegi_db')
DB_USER = config('DB_USER', default='kibegi_user')
DB_PASSWORD = config('DB_PASSWORD', default='')
DB_HOST = config('DB_HOST', default='localhost')
DB_PORT = config('DB_PORT', default='5432', cast=int)

if DB_ENGINE == 'django.db.backends.postgresql':
    # PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'connect_timeout': 10,
            },
            # Connection pooling settings (optional, for production)
            'CONN_MAX_AGE': 600,  # 10 minutes
        }
    }
else:
    # SQLite configuration (default for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []  # Add custom static directories here if needed

# Static files storage configuration
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files (user uploads)
# Must be an absolute path prefix so clients receive stable URLs like `/media/...`.
# A relative prefix (e.g. `media/`) causes `request.build_absolute_uri()` to join
# against the current API path (e.g. `/api/v1/auth/login/media/...`) which breaks
# profile picture rendering in the frontend.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
# Maximum size for files uploaded via POST (50MB to match user storage limit)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes

# MinIO / S3-compatible storage configuration
MINIO_ENABLED = config('MINIO_ENABLED', default=True, cast=bool)
MINIO_API_ENDPOINT = config('MINIO_API_ENDPOINT', default='')
MINIO_ACCESS_KEY = config(
    'MINIO_ACCESS_KEY',
    default=config('AWS_ACCESS_KEY_ID', default='MINIO_ACCESS_KEY'),
)
MINIO_SECRET_KEY = config(
    'MINIO_SECRET_KEY',
    default=config('AWS_SECRET_ACCESS_KEY', default='MINIO_SECRET_KEY'),
)
MINIO_BUCKET = config(
    'MINIO_BUCKET',
    default=config('AWS_STORAGE_BUCKET_NAME', default='kibegi-uploads'),
)
MINIO_SECURE = config(
    'MINIO_SECURE',
    default=config('AWS_S3_USE_SSL', default=True, cast=bool),
    cast=bool,
)
MINIO_PUBLIC_BASE_URL = config('MINIO_PUBLIC_BASE_URL', default='')

if MINIO_API_ENDPOINT and not MINIO_API_ENDPOINT.startswith(('http://', 'https://')):
    _minio_scheme = 'https' if MINIO_SECURE else 'http'
    MINIO_ENDPOINT_URL = f'{_minio_scheme}://{MINIO_API_ENDPOINT}'
else:
    MINIO_ENDPOINT_URL = MINIO_API_ENDPOINT or config(
        'AWS_S3_ENDPOINT_URL',
        default='https://storage.kibegi.com',
    )

STORAGES = {
    "default": {
        "BACKEND": (
            "storages.backends.s3boto3.S3Boto3Storage"
            if MINIO_ENABLED
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

AWS_ACCESS_KEY_ID = MINIO_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = MINIO_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = MINIO_BUCKET
AWS_S3_ENDPOINT_URL = MINIO_ENDPOINT_URL
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_USE_SSL = MINIO_SECURE
AWS_S3_VERIFY = config('AWS_S3_VERIFY', default=MINIO_SECURE, cast=bool)
AWS_QUERYSTRING_AUTH = config('AWS_QUERYSTRING_AUTH', default=False, cast=bool)
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_S3_MAX_MEMORY_SIZE = 52428800
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_EXPIRE = config('AWS_QUERYSTRING_EXPIRE', default=3600, cast=int)
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_LOCATION = ''

if MINIO_PUBLIC_BASE_URL:
    MEDIA_URL = MINIO_PUBLIC_BASE_URL.rstrip('/') + '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'authentication.User'

# REST framework (basic) configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings for Swagger documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Kibegi Digital School API',
    'DESCRIPTION': 'API documentation for Kibegi Digital School platform with JWT authentication',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    
    # JWT Authentication configuration
    'SECURITY': [
        {
            'bearerAuth': [],
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Enter your JWT access token in the format: <token>'
            }
        }
    },
    
    # Swagger UI settings
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    
    # API grouping
    'TAGS': [
        {'name': 'Search', 'description': 'Global search across all apps'},
        {'name': 'Authentication', 'description': 'User authentication and profile management'},
        {'name': 'Classes', 'description': 'Class management and membership'},
        {'name': 'Uploads', 'description': 'File upload and management'},
        {'name': 'Friends', 'description': 'Friend management and requests'},
        {'name': 'Storage', 'description': 'User storage usage tracking and management'},
    ],
}

# Simple JWT settings (basic)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS Configuration - Properly configured for production and development
CORS_ALLOWED_ORIGINS = [
    "https://kibegi.com",
    "https://www.kibegi.com",
    "http://localhost:5173",  # For local development (Vite)
    "http://localhost:8093",  # Frontend dev server used in this workspace
    "http://localhost:4173",  # For local preview
    "http://localhost:3000",  # Alternative dev port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8093",
]

# Set to False since we're using Bearer tokens, not cookies
CORS_ALLOW_CREDENTIALS = False

# Allow necessary headers including Authorization for Bearer tokens
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow necessary HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Expose headers for blob/file responses
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'Content-Disposition',
    'Content-Length',
]

# Load email and other secrets from environment (.env) using python-decouple
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'webmaster@localhost')

# OTP settings
OTP_EXPIRY_SECONDS = config('OTP_EXPIRY_SECONDS', default=300, cast=int)
OTP_LENGTH = config('OTP_LENGTH', default=6, cast=int)

# Schedule app configuration
# This URL is returned to the frontend so it can open a dedicated schedule
# subscription screen instead of relying only on backend-rendered pages.
SCHEDULE_FRONTEND_URL = config('SCHEDULE_FRONTEND_URL', default='')

# Cache configuration
REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
            'OPTIONS': {
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
                'retry_on_timeout': True,
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'kibegi-local-cache',
            'TIMEOUT': 300,
        }
    }


# Logging configuration - write structured logs to a rotating file and upload to MinIO
import logging
from logging.handlers import RotatingFileHandler

LOG_DIR = BASE_DIR / 'logs'
LOG_FILE = LOG_DIR / 'kibegi_api.log'

# Enable MinIO log uploads (set to False to disable)
ENABLE_MINIO_LOG_UPLOAD = config('ENABLE_MINIO_LOG_UPLOAD', default=True, cast=bool)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'apps.core.utils.log_handler.MinIORotatingFileHandler' if ENABLE_MINIO_LOG_UPLOAD else 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_FILE),
            'maxBytes': 1024 * 1024 * 5,  # 5MB - will upload to MinIO when rotated
            'backupCount': 5,
            'formatter': 'standard',
            'bucket_name': config('AWS_STORAGE_BUCKET_NAME', default='kibegi-uploads'),
            's3_prefix': 'logs',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'kibegi': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}
