# Generated by Django 6.0.5 on 2026-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Lecturers must be approved by an admin before they can log in. Students are approved automatically.', verbose_name='approved'),
        ),
    ]
