# Generated by Django 6.0.5 on 2026-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0007_phone_verified_and_phone_otp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__gt', '')), fields=('phone_number',), name='unique_non_empty_user_phone_number'),
        ),
    ]
