# Generated by Django 5.2.8 on 2025-11-22 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('uploads', '0002_upload_file_type_alter_upload_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='class_obj',
            field=models.ForeignKey(default='665f6af4-b52f-415f-ab30-6f0ba182db70', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='classes.class'),
        ),
    ]
