# Generated by Django 5.2.8 on 2025-11-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_is_verified'),
        ('uploads', '0003_alter_upload_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='classes.class'),
        ),
    ]
