# Generated by Django 6.0.5 on 2026-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('share_request', 'Share Request'), ('share_accepted', 'Share Accepted'), ('share_rejected', 'Share Rejected'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('upload_created', 'Upload Created'), ('class_joined', 'Class Joined'), ('file_shared', 'File Shared')], help_text='Type of notification', max_length=30),
        ),
    ]
