# Generated by Django 6.0.5 on 2026-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('share_request', 'Share Request'), ('share_accepted', 'Share Accepted'), ('share_rejected', 'Share Rejected'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('upload_created', 'Upload Created'), ('class_joined', 'Class Joined'), ('class_update', 'Class Update'), ('assignment_created', 'Assignment Created'), ('assignment_due_soon', 'Assignment Due Soon'), ('schedule_reminder', 'Schedule Reminder'), ('file_shared', 'File Shared')], help_text='Type of notification', max_length=30),
        ),
    ]
